CREATE TABLE IF NOT EXISTS trade_order (
    id BIGINT PRIMARY KEY,
    account_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    idempotency_key VARCHAR(64) NOT NULL,
    client_order_no VARCHAR(64) NOT NULL,
    external_order_no VARCHAR(100),
    symbol VARCHAR(32) NOT NULL,
    security_name VARCHAR(100),
    side VARCHAR(10) NOT NULL,
    order_type VARCHAR(20) NOT NULL,
    quantity DECIMAL(20,4) NOT NULL,
    price DECIMAL(20,6),
    filled_quantity DECIMAL(20,4) NOT NULL DEFAULT 0,
    average_filled_price DECIMAL(20,6),
    status VARCHAR(30) NOT NULL,
    environment VARCHAR(20) NOT NULL,
    remark VARCHAR(200),
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uk_order_client_no (client_order_no),
    UNIQUE KEY uk_order_user_idempotency (user_id, idempotency_key),
    KEY idx_order_account_created (account_id, created_at DESC),
    KEY idx_order_account_status_created (account_id, status, created_at DESC),
    CONSTRAINT fk_order_account FOREIGN KEY (account_id) REFERENCES account(id),
    CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES sys_user(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
