CREATE TABLE IF NOT EXISTS account_snapshot (
    id BIGINT PRIMARY KEY,
    account_id BIGINT NOT NULL,
    snapshot_time DATETIME(3) NOT NULL,
    snapshot_type VARCHAR(20) NOT NULL,
    total_asset DECIMAL(20,4) NOT NULL DEFAULT 0,
    cash DECIMAL(20,4) NOT NULL DEFAULT 0,
    market_value DECIMAL(20,4) NOT NULL DEFAULT 0,
    profit_loss DECIMAL(20,4) NOT NULL DEFAULT 0,
    position_count INT NOT NULL DEFAULT 0,
    positions_captured TINYINT(1) NOT NULL DEFAULT 0,
    source VARCHAR(32) NOT NULL,
    data_version VARCHAR(96) NOT NULL,
    source_record_id VARCHAR(64),
    created_at DATETIME(3) NOT NULL,
    UNIQUE KEY uk_account_snapshot_version (account_id, data_version, snapshot_type),
    UNIQUE KEY uk_account_snapshot_source_record (source_record_id),
    KEY idx_account_snapshot_time (account_id, snapshot_time DESC),
    KEY idx_account_snapshot_type_time (account_id, snapshot_type, snapshot_time DESC),
    KEY idx_account_snapshot_positions_time (account_id, positions_captured, snapshot_time DESC),
    CONSTRAINT fk_account_snapshot_account FOREIGN KEY (account_id) REFERENCES account(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS position_snapshot (
    id BIGINT PRIMARY KEY,
    snapshot_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    snapshot_time DATETIME(3) NOT NULL,
    security_code VARCHAR(32) NOT NULL,
    security_name VARCHAR(100),
    quantity DECIMAL(20,4) NOT NULL DEFAULT 0,
    available_quantity DECIMAL(20,4) NOT NULL DEFAULT 0,
    cost_price DECIMAL(20,6),
    last_price DECIMAL(20,6),
    market_value DECIMAL(20,4),
    profit_loss DECIMAL(20,4),
    industry VARCHAR(100),
    region VARCHAR(100),
    created_at DATETIME(3) NOT NULL,
    UNIQUE KEY uk_position_snapshot_symbol (snapshot_id, security_code),
    KEY idx_position_snapshot_account_time (account_id, snapshot_time DESC),
    KEY idx_position_snapshot_symbol_time (account_id, security_code, snapshot_time DESC),
    CONSTRAINT fk_position_snapshot_snapshot FOREIGN KEY (snapshot_id) REFERENCES account_snapshot(id),
    CONSTRAINT fk_position_snapshot_account FOREIGN KEY (account_id) REFERENCES account(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
