CREATE TABLE IF NOT EXISTS risk_assessment (
    id BIGINT PRIMARY KEY,
    task_id BIGINT,
    account_id BIGINT NOT NULL,
    range_start DATE,
    range_end DATE,
    risk_level VARCHAR(20) NOT NULL,
    risk_score DECIMAL(10,4) NOT NULL DEFAULT 0,
    metrics_json JSON NOT NULL,
    recommendations_json JSON NOT NULL,
    sample_json JSON NOT NULL,
    warnings_json JSON NOT NULL,
    data_version VARCHAR(128) NOT NULL,
    rule_version INT,
    algorithm_version VARCHAR(64),
    environment VARCHAR(20),
    data_source VARCHAR(32),
    source_record_id VARCHAR(64),
    calculated_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    UNIQUE KEY uk_risk_assessment_source_record (source_record_id),
    KEY idx_risk_account_time (account_id, calculated_at DESC),
    KEY idx_risk_account_version (account_id, data_version),
    KEY idx_risk_task (task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
