CREATE TABLE IF NOT EXISTS quant_task (
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    account_id BIGINT,
    task_type VARCHAR(40) NOT NULL,
    status VARCHAR(24) NOT NULL,
    progress INT NOT NULL DEFAULT 0,
    stage VARCHAR(200),
    input_data_version VARCHAR(128),
    request_json JSON NOT NULL,
    result_type VARCHAR(40),
    result_id BIGINT,
    result_summary_json JSON,
    error_code VARCHAR(64),
    error_message VARCHAR(1000),
    retry_count INT NOT NULL DEFAULT 0,
    max_retries INT NOT NULL DEFAULT 0,
    idempotency_key VARCHAR(96),
    created_at DATETIME(3) NOT NULL,
    started_at DATETIME(3),
    finished_at DATETIME(3),
    updated_at DATETIME(3) NOT NULL,
    UNIQUE KEY uk_quant_task_user_idem (user_id, task_type, idempotency_key),
    KEY idx_quant_task_status_created (status, created_at),
    KEY idx_quant_task_user_created (user_id, created_at DESC),
    KEY idx_quant_task_account_type (account_id, task_type, created_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
